name: py34
dependencies:
- _nb_ext_conf=0.2.0=py34_0
- alabaster=0.7.8=py34_0
- anaconda=4.1.1=np111py34_0
- anaconda-client=1.4.0=py34_0
- anaconda-navigator=1.2.1=py34_0
- argcomplete=1.0.0=py34_1
- astropy=1.2.1=np111py34_0
- babel=2.3.3=py34_0
- backports=1.0=py34_0
- backports_abc=0.4=py34_0
- beautifulsoup4=4.4.1=py34_0
- bitarray=0.8.1=py34_0
- blaze=0.10.1=py34_0
- bokeh=0.12.0=py34_0
- boto=2.40.0=py34_0
- bottleneck=1.1.0=np111py34_0
- bzip2=1.0.6=3
- cairo=1.14.8=0
- cffi=1.6.0=py34_0
- chest=0.2.3=py34_0
- click=6.6=py34_0
- cloudpickle=0.2.1=py34_0
- clyent=1.2.2=py34_0
- colorama=0.3.7=py34_0
- configobj=5.0.6=py34_0
- contextlib2=0.5.3=py34_0
- cryptography=1.4=py34_0
- curl=7.52.1=0
- cycler=0.10.0=py34_0
- cython=0.24=py34_0
- cytoolz=0.8.0=py34_0
- dask=0.10.0=py34_0
- datashape=0.5.2=py34_0
- dbus=1.10.10=0
- decorator=4.0.10=py34_0
- dill=0.2.5=py34_0
- docutils=0.12=py34_2
- entrypoints=0.2.2=py34_0
- et_xmlfile=1.0.1=py34_0
- expat=2.1.0=0
- fastcache=1.0.2=py34_1
- flask=0.11.1=py34_0
- flask-cors=2.1.2=py34_0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- get_terminal_size=1.0.0=py34_0
- gevent=1.1.1=py34_0
- glib=2.50.2=1
- greenlet=0.4.10=py34_0
- gsl=2.2.1=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- h5py=2.6.0=np111py34_1
- harfbuzz=0.9.39=2
- hddm=0.6.0=py34_0
- hdf5=1.8.16=0
- heapdict=1.0.0=py34_1
- icu=54.1=0
- idna=2.1=py34_0
- imagesize=0.7.1=py34_0
- ipykernel=4.3.1=py34_0
- ipython=4.2.0=py34_0
- ipython_genutils=0.1.0=py34_0
- ipywidgets=4.1.1=py34_0
- itsdangerous=0.24=py34_0
- jbig=2.1=0
- jdcal=1.2=py34_1
- jedi=0.9.0=py34_1
- jinja2=2.8=py34_1
- jpeg=9b=0
- jsonschema=2.5.1=py34_0
- jupyter=1.0.0=py34_3
- jupyter_client=4.3.0=py34_0
- jupyter_console=4.1.1=py34_0
- jupyter_core=4.1.0=py34_0
- kabuki=0.6.1=py34_0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libsodium=1.0.10=0
- libtiff=4.0.6=3
- libxcb=1.12=1
- libxml2=2.9.4=0
- libxslt=1.1.28=0
- llvmlite=0.11.0=py34_0
- locket=0.2.0=py34_1
- lxml=3.6.0=py34_0
- markupsafe=0.23=py34_2
- matplotlib=1.5.3=np111py34_1
- mistune=0.7.2=py34_0
- mkl=11.3.3=0
- mkl-service=1.1.2=py34_2
- mpmath=0.19=py34_1
- multipledispatch=0.4.8=py34_0
- nb_anacondacloud=1.1.0=py34_0
- nb_conda=1.1.0=py34_0
- nb_conda_kernels=1.0.3=py34_0
- nbconvert=4.2.0=py34_0
- nbformat=4.0.1=py34_0
- nbpresent=3.0.2=py34_0
- ncurses=5.9=10
- networkx=1.11=py34_0
- nltk=3.2.1=py34_0
- nose=1.3.7=py34_1
- notebook=4.2.1=py34_0
- numba=0.26.0=np111py34_0
- numexpr=2.6.0=np111py34_0
- numpy=1.11.2=py34_0
- odo=0.5.0=py34_1
- openpyxl=2.3.2=py34_0
- openssl=1.0.2l=0
- pandas=0.19.0=np111py34_0
- pango=1.40.3=1
- partd=0.3.4=py34_0
- patchelf=0.9=0
- path.py=8.2.1=py34_0
- pathlib2=2.1.0=py34_0
- patsy=0.4.1=py34_0
- pcre=8.39=1
- pep8=1.7.0=py34_0
- pexpect=4.0.1=py34_0
- pickleshare=0.7.2=py34_0
- pillow=3.2.0=py34_1
- pip=9.0.1=py34_1
- pixman=0.34.0=0
- ply=3.8=py34_0
- psutil=4.3.0=py34_0
- ptyprocess=0.5.1=py34_0
- py=1.4.31=py34_0
- pyasn1=0.1.9=py34_0
- pycosat=0.6.1=py34_1
- pycparser=2.14=py34_1
- pycrypto=2.6.1=py34_4
- pycurl=7.43.0=py34_0
- pyflakes=1.2.3=py34_0
- pygments=2.1.3=py34_0
- pymc=2.3.6=np111py34_2
- pyopenssl=0.16.0=py34_0
- pyparsing=2.1.4=py34_0
- pyqt=5.6.0=py34_0
- pytables=3.2.2=np111py34_4
- pytest=2.9.2=py34_0
- python=3.4.5=0
- python-dateutil=2.5.3=py34_0
- pytz=2016.7=py34_0
- pyyaml=3.11=py34_4
- pyzmq=15.2.0=py34_1
- qt=5.6.0=1
- qtconsole=4.2.1=py34_0
- qtpy=1.0.2=py34_0
- r=3.3.2=r3.3.2_0
- r-base=3.3.2=1
- r-boot=1.3_18=r3.3.2_0
- r-class=7.3_14=r3.3.2_0
- r-cluster=2.0.5=r3.3.2_0
- r-codetools=0.2_15=r3.3.2_0
- r-foreign=0.8_67=r3.3.2_0
- r-kernsmooth=2.23_15=r3.3.2_0
- r-lattice=0.20_34=r3.3.2_0
- r-mass=7.3_45=r3.3.2_0
- r-matrix=1.2_7.1=r3.3.2_0
- r-mgcv=1.8_16=r3.3.2_0
- r-nlme=3.1_128=r3.3.2_0
- r-nnet=7.3_12=r3.3.2_0
- r-recommended=3.3.2=r3.3.2_0
- r-rpart=4.1_10=r3.3.2_0
- r-spatial=7.3_11=r3.3.2_0
- r-survival=2.40_1=r3.3.2_0
- readline=6.2=2
- redis=3.2.0=0
- redis-py=2.10.5=py34_0
- requests=2.10.0=py34_0
- rope=0.9.4=py34_1
- rpy2=2.8.5=py34r3.3.2_2
- ruamel_yaml=0.11.7=py34_0
- scikit-image=0.12.3=np111py34_1
- scikit-learn=0.17.1=np111py34_2
- scipy=0.18.1=np111py34_0
- setuptools=27.2.0=py34_0
- simplegeneric=0.8.1=py34_1
- singledispatch=3.4.0.3=py34_0
- sip=4.18=py34_0
- six=1.10.0=py34_0
- snowballstemmer=1.2.1=py34_0
- sockjs-tornado=1.0.3=py34_0
- sphinx=1.4.1=py34_0
- sphinx_rtd_theme=0.1.9=py34_0
- spyder=2.3.9=py34_0
- sqlalchemy=1.0.13=py34_0
- sqlite=3.13.0=0
- statsmodels=0.6.1=np111py34_1
- sympy=1.0=py34_0
- terminado=0.6=py34_0
- tk=8.5.18=0
- toolz=0.8.0=py34_0
- tornado=4.3=py34_1
- traitlets=4.2.1=py34_0
- unicodecsv=0.14.1=py34_0
- werkzeug=0.11.10=py34_0
- wheel=0.29.0=py34_0
- xlrd=1.0.0=py34_0
- xlsxwriter=0.9.2=py34_0
- xlwt=1.1.2=py34_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zeromq=4.1.4=0
- zlib=1.2.8=3
- pip:
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - et-xmlfile==1.0.1
  - expanalysis (/home/ieisenbe/software/expfactory-analysis)==0.0.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.3.0
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - nb-anacondacloud==1.1.0
  - nb-conda==1.1.0
  - nb-conda-kernels==1.0.3
  - neurodesign==0.0.13
  - prompt-toolkit==1.0.9
  - reportlab==3.3.0
  - rope-py3k==0.9.4.post1
  - ruamel-yaml-==VERSION
  - seaborn==0.7.1
  - selfregulation (/home/ieisenbe/.conda/envs/py34/lib/python3.4/site-packages/selfregulation-0.1.0.dev0-py3.4.egg)==0.1.0.dev0
  - sphinx-rtd-theme==0.1.9
  - tables==3.2.2
  - wcwidth==0.1.7

