name: py34
channels: !!python/tuple
- r
- conda-forge
- defaults
dependencies:
- _license=1.1=py34_1
- _nb_ext_conf=0.3.0=py34_0
- alabaster=0.7.9=py34_0
- anaconda-clean=1.0.3=py34_0
- anaconda-client=1.6.0=py34_0
- anaconda=custom=py34_0
- anaconda-navigator=1.5.0=py34_0
- anaconda-project=0.4.1=py34_0
- argcomplete=1.0.0=py34_1
- astroid=1.4.9=py34_0
- astropy=1.3=np111py34_0
- babel=2.3.4=py34_0
- backports=1.0=py34_0
- backports_abc=0.5=py34_0
- beautifulsoup4=4.5.3=py34_0
- bitarray=0.8.1=py34_0
- blaze=0.10.1=py34_0
- bokeh=0.12.4=py34_0
- boto=2.45.0=py34_0
- bottleneck=1.2.0=np111py34_0
- bzip2=1.0.6=3
- cairo=1.14.8=0
- cffi=1.9.1=py34_0
- chardet=2.3.0=py34_0
- chest=0.2.3=py34_0
- click=6.7=py34_0
- cloog=0.18.0=0
- cloudpickle=0.2.2=py34_0
- clyent=1.2.2=py34_0
- colorama=0.3.7=py34_0
- conda-forge::jupyter_contrib_core=0.3.0=py34_1
- conda-forge::jupyter_contrib_nbextensions=0.2.3=py34_0
- conda-forge::jupyter_highlight_selected_word=0.0.7=py34_0
- conda-forge::jupyter_latex_envs=1.3.6=py34_0
- conda-forge::jupyter_nbextensions_configurator=0.2.3=py34_0
- conda-forge::libiconv=1.14=4
- configobj=5.0.6=py34_0
- contextlib2=0.5.4=py34_0
- cryptography=1.7.1=py34_0
- curl=7.52.1=0
- cycler=0.10.0=py34_0
- cython=0.25.2=py34_0
- cytoolz=0.8.2=py34_0
- dask=0.13.0=py34_0
- datashape=0.5.4=py34_0
- dbus=1.10.10=0
- decorator=4.0.11=py34_0
- dill=0.2.5=py34_0
- docutils=0.13.1=py34_0
- entrypoints=0.2.2=py34_0
- et_xmlfile=1.0.1=py34_0
- expat=2.1.0=0
- fastcache=1.0.2=py34_1
- filelock=2.0.7=py34_0
- flask=0.12=py34_0
- flask-cors=3.0.2=py34_0
- fontconfig=2.12.1=2
- freetype=2.5.5=2
- gcc=4.8.5=7
- get_terminal_size=1.0.0=py34_0
- gevent=1.2.1=py34_0
- glib=2.50.2=1
- gmp=6.1.0=0
- greenlet=0.4.11=py34_0
- gsl=2.2.1=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- h5py=2.6.0=np111py34_2
- harfbuzz=0.9.39=2
- hdf5=1.8.17=1
- heapdict=1.0.0=py34_1
- icu=54.1=0
- idna=2.2=py34_0
- imagesize=0.7.1=py34_0
- ipykernel=4.5.2=py34_0
- ipython=5.1.0=py34_0
- ipython_genutils=0.1.0=py34_0
- ipywidgets=5.2.2=py34_1
- isl=0.12.2=0
- isort=4.2.5=py34_0
- itsdangerous=0.24=py34_0
- jbig=2.1=0
- jdcal=1.3=py34_0
- jedi=0.9.0=py34_1
- jinja2=2.9.4=py34_0
- jpeg=9b=0
- jsonschema=2.5.1=py34_0
- jupyter=1.0.0=py34_3
- jupyter_client=4.4.0=py34_0
- jupyter_console=5.0.0=py34_0
- jupyter_core=4.2.1=py34_0
- keras=1.1.1=py34_0
- lazy-object-proxy=1.2.2=py34_0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libpng=1.6.27=0
- libprotobuf=3.0.0=0
- libsodium=1.0.10=0
- libtiff=4.0.6=3
- libxcb=1.12=1
- libxml2=2.9.4=0
- libxslt=1.1.29=0
- llvmlite=0.15.0=py34_0
- locket=0.2.0=py34_1
- lxml=3.7.2=py34_0
- markupsafe=0.23=py34_2
- matplotlib=2.0.0=np111py34_0
- mistune=0.7.3=py34_0
- mkl=2017.0.1=0
- mkl-service=1.1.2=py34_3
- mock=2.0.0=py34_0
- mpc=1.0.3=0
- mpfr=3.1.5=0
- mpmath=0.19=py34_1
- multipledispatch=0.4.9=py34_0
- nb_anacondacloud=1.2.0=py34_0
- nb_conda=2.0.0=py34_0
- nb_conda_kernels=2.0.0=py34_0
- nbconvert=4.2.0=py34_0
- nbformat=4.2.0=py34_0
- nbpresent=3.0.2=py34_0
- ncurses=5.9=10
- networkx=1.11=py34_0
- nltk=3.2.2=py34_0
- nomkl=1.0=0
- nose=1.3.7=py34_1
- notebook=4.3.1=py34_0
- numba=0.30.1=np111py34_0
- numexpr=2.6.1=np111py34_nomkl_2
- numpy=1.11.3=py34_nomkl_0
- numpydoc=0.6.0=py34_0
- odo=0.5.0=py34_1
- openblas=0.2.19=0
- openpyxl=2.4.1=py34_0
- openssl=1.0.2k=1
- pandas=0.19.2=np111py34_1
- pango=1.40.3=1
- partd=0.3.7=py34_0
- patchelf=0.9=0
- path.py=10.0=py34_0
- pathlib2=2.2.0=py34_0
- patsy=0.4.1=py34_0
- pbr=1.10.0=py34_0
- pcre=8.39=1
- pep8=1.7.0=py34_0
- pexpect=4.2.1=py34_0
- pickleshare=0.7.4=py34_0
- pillow=4.0.0=py34_0
- pip=9.0.1=py34_1
- pixman=0.34.0=0
- pkginfo=1.4.1=py34_0
- ply=3.9=py34_0
- prompt_toolkit=1.0.9=py34_0
- protobuf=3.0.0=py34_0
- psutil=5.0.1=py34_0
- ptyprocess=0.5.1=py34_0
- py=1.4.32=py34_0
- pyasn1=0.1.9=py34_0
- pycosat=0.6.1=py34_1
- pycparser=2.17=py34_0
- pycrypto=2.6.1=py34_4
- pycurl=7.43.0=py34_2
- pyflakes=1.5.0=py34_0
- pygments=2.1.3=py34_0
- pylint=1.6.4=py34_1
- pymc=2.3.6=np111py34_nomkl_2
- pymc::hddm=0.6.0=py34_0
- pymc::kabuki=0.6.1=py34_0
- pyopenssl=16.2.0=py34_0
- pyparsing=2.1.4=py34_0
- pyqt=5.6.0=py34_2
- pytables=3.3.0=np111py34_0
- pytest=3.0.5=py34_0
- python=3.4.5=0
- python-dateutil=2.6.0=py34_0
- pytz=2016.10=py34_0
- pyyaml=3.12=py34_0
- pyzmq=16.0.2=py34_0
- qt=5.6.2=3
- qtawesome=0.4.3=py34_0
- qtconsole=4.2.1=py34_1
- qtpy=1.2.1=py34_0
- r::r=3.3.2=r3.3.2_0
- r::r-base=3.3.2=1
- r::r-boot=1.3_18=r3.3.2_0
- r::r-class=7.3_14=r3.3.2_0
- r::r-cluster=2.0.5=r3.3.2_0
- r::r-codetools=0.2_15=r3.3.2_0
- r::r-foreign=0.8_67=r3.3.2_0
- r::r-kernsmooth=2.23_15=r3.3.2_0
- r::r-lattice=0.20_34=r3.3.2_0
- r::r-mass=7.3_45=r3.3.2_0
- r::r-matrix=1.2_7.1=r3.3.2_0
- r::r-mgcv=1.8_16=r3.3.2_0
- r::r-nlme=3.1_128=r3.3.2_0
- r::r-nnet=7.3_12=r3.3.2_0
- r::r-recommended=3.3.2=r3.3.2_0
- r::r-rpart=4.1_10=r3.3.2_0
- r::r-spatial=7.3_11=r3.3.2_0
- r::r-survival=2.40_1=r3.3.2_0
- r::rpy2=2.8.5=py34r3.3.2_2
- readline=6.2=2
- redis=3.2.0=0
- redis-py=2.10.5=py34_0
- requests=2.12.4=py34_0
- rope=0.9.4=py34_1
- ruamel_yaml=0.11.14=py34_1
- scandir=1.4=py34_0
- scikit-image=0.12.3=np111py34_1
- scikit-learn=0.18.1=np111py34_nomkl_1
- scipy=0.18.1=np111py34_nomkl_1
- seaborn=0.7.1=py34_0
- setuptools=27.2.0=py34_0
- simplegeneric=0.8.1=py34_1
- singledispatch=3.4.0.3=py34_0
- sip=4.18=py34_0
- six=1.10.0=py34_0
- snowballstemmer=1.2.1=py34_0
- sockjs-tornado=1.0.3=py34_0
- sphinx=1.5.1=py34_0
- spyder=3.1.2=py34_0
- sqlalchemy=1.1.5=py34_0
- sqlite=3.13.0=0
- statsmodels=0.6.1=np111py34_1
- sympy=1.0=py34_0
- tensorflow=0.10.0rc0=np111py34_0
- terminado=0.6=py34_0
- theano=0.8.2=py34_0
- tk=8.5.18=0
- toolz=0.8.2=py34_0
- tornado=4.4.2=py34_0
- traitlets=4.3.1=py34_0
- unicodecsv=0.14.1=py34_0
- wcwidth=0.1.7=py34_0
- werkzeug=0.11.15=py34_0
- wheel=0.29.0=py34_0
- widgetsnbextension=1.2.6=py34_0
- wrapt=1.10.8=py34_0
- xlrd=1.0.0=py34_0
- xlsxwriter=0.9.6=py34_0
- xlwt=1.2.0=py34_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - appdirs==1.4.2
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - bctpy==0.5.0
  - bleach==1.5.0
  - cairocffi==0.7.2
  - climate==0.4.6
  - cvxcanon==0.1.1
  - cvxpy==0.4.8
  - downhill==0.3.2
  - ecos==2.0.4
  - et-xmlfile==1.0.1
  - fancyimpute==0.0.19
  - functional==0.4
  - future==0.16.0
  - html5lib==0.9999999
  - ijson==2.3
  - ipython-genutils==0.1.0
  - isodate==0.5.4
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-contrib-core==0.3.0
  - jupyter-contrib-nbextensions==0.2.3
  - jupyter-core==4.3.0
  - jupyter-highlight-selected-word==0.0.7
  - jupyter-latex-envs==1.3.6
  - jupyter-nbextensions-configurator==0.2.3
  - knnimpute==0.0.1
  - lmfit==0.9.5
  - mccabe==0.6.1
  - mpld3==0.3
  - mtspec==0.3.2
  - multiprocess==0.70.4
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - nibabel==2.1.0
  - nipy==0.4.0
  - nipype==0.12.1
  - packaging==16.8
  - pandocfilters==1.4.1
  - plac==0.9.6
  - prompt-toolkit==1.0.9
  - prov==1.5.0
  - python-igraph==0.7.1.post6
  - rdflib==4.2.1
  - rope-py3k==0.9.4.post1
  - scs==1.2.6
  - simplejson==3.10.0
  - tables==3.3.0
  - testpath==0.3
  - traits==4.6.0
  - xvfbwrapper==0.2.9

# r packages that are necessary for rpy2
# - psych
# - missforest
# - qgraph

