version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda
    steps:
      - checkout
      - run:
          name: Install Python deps in a virtual environment
          command: |
            sudo apt-get install -y default-jre gfortran
            conda update conda
            conda install --yes anaconda-client anaconda-build conda-build
            conda config --add channels r
            conda install --yes numpy pytest r r-essentials numpy pandas scikit-learn imbalanced-learn nilearn scipy matplotlib networkx statsmodels
            pip install rpy2 jinja2 ipdb fancyimpute IPython
            echo "install.packages(c("mpath","glmnet","foreach","iterators","pscl","numDeriv","doParallel"),repos="http://cran.us.r-project.org", dependencies=TRUE)" | R --vanilla
      - run:
          command: |
            pytest
